"""Source-owned vocabulary for canonical changeset derivation."""

from __future__ import annotations

BRANCH_SLUG_COLLISION_SUFFIX_LENGTH = 8
BRANCH_SLUG_MAX_LENGTH = 64
BRANCH_REF_PATH_SEPARATOR = "/"
BRANCH_SLUG_PATH_SUBSTITUTE = "__"
BRANCH_SLUG_DOT_SUBSTITUTE = "__dot__"
BRANCH_SLUG_DOTDOT_SUBSTITUTE = "__dotdot__"
ORIGIN_REMOTE_NAME = "origin"
ORIGIN_HEAD_REF_PREFIX = f"refs/remotes/{ORIGIN_REMOTE_NAME}/"
ORIGIN_HEAD_REF = f"{ORIGIN_HEAD_REF_PREFIX}HEAD"
ORIGIN_REF_PREFIX = f"{ORIGIN_REMOTE_NAME}/"
HEAD_REF = "HEAD"
BRANCH_SCOPE_RANGE_TEMPLATE = f"{{origin_ref}}...{HEAD_REF}"
FRONTMATTER_DELIMITER = "---"
STATE_FILE_BRANCH_KEY = "branch"
STATE_FILE_SUFFIX = ".md"
COMMIT_PEEL_SUFFIX = "^{commit}"
BRANCH_SLUG_SUFFIX_SEPARATOR = "--"
